package com.qrattend.service;

import com.qrattend.dto.admin.InviteResponse;
import com.qrattend.exception.InvalidCredentialsException;
import com.qrattend.security.JwtUtil;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.security.MessageDigest;

/**
 * Handles admin invite code generation.
 *
 * <p>The admin secret is stored in {@code application.properties} under
 * {@code app.admin.secret}. This endpoint is publicly accessible
 * (no JWT required) but protected by the shared admin secret.</p>
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class AdminService {

    private final JwtUtil jwtUtil;

    @Value("${app.admin.secret}")
    private String adminSecret;

    /**
     * Generates an invite code (INVITE JWT) for professor registration.
     *
     * @param providedSecret the admin secret provided in the request
     * @return the invite code wrapped in an {@link InviteResponse}
     * @throws InvalidCredentialsException if the provided secret doesn't match
     */
    public InviteResponse generateInvite(String providedSecret) {
        // Constant-time comparison to prevent timing attacks
        if (!MessageDigest.isEqual(
                adminSecret.getBytes(),
                providedSecret.getBytes())) {
            throw new InvalidCredentialsException("Invalid admin secret");
        }

        String inviteCode = jwtUtil.generateInviteToken();

        log.info("Invite code generated by admin");

        return new InviteResponse(inviteCode);
    }
}
